// O'zbekiston viloyatlari
export const regions = [
  { value: "toshkent_sh", label: "Toshkent shahri" },
  { value: "toshkent_vil", label: "Toshkent viloyati" },
  { value: "andijon", label: "Andijon viloyati" },
  { value: "fargona", label: "Farg'ona viloyati" },
  { value: "namangan", label: "Namangan viloyati" },
  { value: "sirdaryo", label: "Sirdaryo viloyati" },
  { value: "jizzax", label: "Jizzax viloyati" },
  { value: "samarqand", label: "Samarqand viloyati" },
  { value: "qashqadaryo", label: "Qashqadaryo viloyati" },
  { value: "surxondaryo", label: "Surxondaryo viloyati" },
  { value: "buxoro", label: "Buxoro viloyati" },
  { value: "navoiy", label: "Navoiy viloyati" },
  { value: "xorazm", label: "Xorazm viloyati" },
  { value: "qoraqalpogiston", label: "Qoraqalpog'iston Respublikasi" },
]

// Tumanlar (viloyatlar bo'yicha)
export const districtsByRegion: Record<string, { value: string; label: string }[]> = {
  toshkent_sh: [
    { value: "bektemir", label: "Bektemir tumani" },
    { value: "chilonzor", label: "Chilonzor tumani" },
    { value: "mirzo_ulugbek", label: "Mirzo Ulug'bek tumani" },
    { value: "olmazor", label: "Olmazor tumani" },
    { value: "sergeli", label: "Sergeli tumani" },
    { value: "shayxontoxur", label: "Shayxontoxur tumani" },
    { value: "uchtepa", label: "Uchtepa tumani" },
    { value: "yunusobod", label: "Yunusobod tumani" },
    { value: "yakkasaroy", label: "Yakkasaroy tumani" },
  ],
  toshkent_vil: [
    { value: "bekobod", label: "Bekobod tumani" },
    { value: "boka", label: "Bo'ka tumani" },
    { value: "chinoz", label: "Chinoz tumani" },
    { value: "ohangaron", label: "Ohangaron tumani" },
    { value: "olmaliq", label: "Olmaliq shahri" },
    { value: "piskent", label: "Piskent tumani" },
    { value: "quyichirchiq", label: "Quyi Chirchiq tumani" },
    { value: "toshkent_tum", label: "Toshkent tumani" },
    { value: "uyt", label: "O'rtachirchiq tumani" },
    { value: "yangiyoq", label: "Yangiyo'l tumani" },
    { value: "zangiota", label: "Zangiota tumani" },
  ],
  andijon: [
    { value: "andijon_sh", label: "Andijon shahri" },
    { value: "asaka", label: "Asaka tumani" },
    { value: "baliqchi", label: "Baliqchi tumani" },
    { value: "bulungur", label: "Bulung'ur tumani" },
    { value: "boston", label: "Bo'ston tumani" },
    { value: "jalaquduq", label: "Jalaquduq tumani" },
    { value: "ixo", label: "Izboskan tumani" },
    { value: "qorgontepa", label: "Qo'rg'ontepa tumani" },
    { value: "marhamat", label: "Marhamat tumani" },
    { value: "paxtaobod", label: "Paxtaobod tumani" },
    { value: "ulugnor", label: "Ulug'nor tumani" },
    { value: "xonobod", label: "Xonobod shahri" },
  ],
  fargona: [
    { value: "fargona_sh", label: "Farg'ona shahri" },
    { value: "beshariq", label: "Beshariq tumani" },
    { value: "buvayda", label: "Buvayda tumani" },
    { value: "dangara", label: "Dang'ara tumani" },
    { value: "yaypan", label: "O'zbekiston tumani" },
    { value: "quva", label: "Quva tumani" },
    { value: "qoqon", label: "Qo'qon shahri" },
    { value: "margilon", label: "Marg'ilon shahri" },
    { value: "rishton", label: "Rishton tumani" },
    { value: "sox", label: "So'x tumani" },
    { value: "toshloq", label: "Toshloq tumani" },
    { value: "uchkoq", label: "Uchko'prik tumani" },
    { value: "furg", label: "Furqat tumani" },
    { value: "qodiriya", label: "Qodiriya tumani" },
  ],
  namangan: [
    { value: "namangan_sh", label: "Namangan shahri" },
    { value: "chortoq", label: "Chortoq tumani" },
    { value: "chust", label: "Chust tumani" },
    { value: "kosonsoy", label: "Kosonsoy tumani" },
    { value: "mingbuloq", label: "Mingbuloq tumani" },
    { value: "namangan_tum", label: "Namangan tumani" },
    { value: "norin", label: "Norin tumani" },
    { value: "pop", label: "Pop tumani" },
    { value: "turobqorgon", label: "Turqo'rg'on tumani" },
    { value: "uych", label: "Uychi tumani" },
    { value: "uqq", label: "Uchqo'rg'on tumani" },
    { value: "yangiqorgon", label: "Yangiqo'rg'on tumani" },
  ],
  sirdaryo: [
    { value: "guliston", label: "Guliston shahri" },
    { value: "boyovut", label: "Boyovut tumani" },
    { value: "gulistan_tum", label: "Guliston tumani" },
    { value: "khavast", label: "Xovas tumani" },
    { value: "mirzaobod", label: "Mirzaobod tumani" },
    { value: "sayxunobod", label: "Sayxunobod tumani" },
    { value: "sirdaryo_tum", label: "Sirdaryo tumani" },
    { value: "sardoba", label: "Sardoba tumani" },
    { value: "shirin", label: "Shirin shahri" },
    { value: "yangiyer", label: "Yangiyer shahri" },
  ],
  jizzax: [
    { value: "jizzax_sh", label: "Jizzax shahri" },
    { value: "arnasoy", label: "Arnasoy tumani" },
    { value: "baxmal", label: "Baxmal tumani" },
    { value: "gallaorol", label: "G'allakorol tumani" },
    { value: "dustlik", label: "Do'stlik tumani" },
    { value: "zafarobod", label: "Zafarobod tumani" },
    { value: "zomin", label: "Zomin tumani" },
    { value: "mirzacho", label: "Mirzacho'l tumani" },
    { value: "paxtakor", label: "Paxtakor tumani" },
    { value: "forish", label: "Forish tumani" },
    { value: "yangiobod", label: "Yangiobod tumani" },
  ],
  samarqand: [
    { value: "samarqand_sh", label: "Samarqand shahri" },
    { value: "bulungur", label: "Bulung'ur tumani" },
    { value: "guzalkent", label: "G'uzalkent tumani" },
    { value: "ishtixon", label: "Ishtixon tumani" },
    { value: "jambay", label: "Jomboy tumani" },
    { value: "kattaqorgon", label: "Kattaqo'rg'on shahri" },
    { value: "kattaqorgon_tum", label: "Kattaqo'rg'on tumani" },
    { value: "koshrabot", label: "Koshrabot tumani" },
    { value: "narpay", label: "Narpay tumani" },
    { value: "nurobod", label: "Nurobod tumani" },
    { value: "oydinqul", label: "Oqdaryo tumani" },
    { value: "pastdargom", label: "Pastdarg'om tumani" },
    { value: "payariq", label: "Payariq tumani" },
    { value: "pakhtachi", label: "Paxtachi tumani" },
    { value: "tayloq", label: "Tayloq tumani" },
    { value: "urgut", label: "Urgut tumani" },
  ],
  qashqadaryo: [
    { value: "qarshi", label: "Qarshi shahri" },
    { value: "chiroqchi", label: "Chiroqchi tumani" },
    { value: "dehqonobod", label: "Dehqonobod tumani" },
    { value: "guzor", label: "G'uzor tumani" },
    { value: "kamashi", label: "Kamashi tumani" },
    { value: "koson", label: "Koson tumani" },
    { value: "muborak", label: "Muborak tumani" },
    { value: "nisfon", label: "Nishon tumani" },
    { value: "shahrisabz", label: "Shahrisabz shahri" },
    { value: "yakkabog", label: "Yakkabog' tumani" },
  ],
  surxondaryo: [
    { value: "termiz", label: "Termiz shahri" },
    { value: "angor", label: "Angor tumani" },
    { value: "bandixon", label: "Bandixon tumani" },
    { value: "boysun", label: "Boysun tumani" },
    { value: "denov", label: "Denov tumani" },
    { value: "jarkurgon", label: "Jarqo'rg'on tumani" },
    { value: "qiziriq", label: "Qiziriq tumani" },
    { value: "qumqorgon", label: "Qumqo'rg'on tumani" },
    { value: "muzrabod", label: "Muzrabod tumani" },
    { value: "oltinsoy", label: "Oltinsoy tumani" },
    { value: "sariosiyo", label: "Sariosiyo tumani" },
    { value: "sherobod", label: "Sherobod tumani" },
    { value: "shurchi", label: "Sho'rchi tumani" },
    { value: "uzun", label: "Uzun tumani" },
  ],
  buxoro: [
    { value: "buxoro_sh", label: "Buxoro shahri" },
    { value: "altinsay", label: "Oltinsoy tumani" },
    { value: "buxoro_tum", label: "Buxoro tumani" },
    { value: "vobkent", label: "Vobkent tumani" },
    { value: "gijduvon", label: "G'ijduvon tumani" },
    { value: "jondor", label: "Jondor tumani" },
    { value: "qorako", label: "Qorako'l tumani" },
    { value: "qorovulbozor", label: "Qorovulbozor tumani" },
    { value: "kogon", label: "Kogon shahri" },
    { value: "peshku", label: "Peshku tumani" },
    { value: "romitan", label: "Romitan tumani" },
    { value: "shofirkon", label: "Shofirkon tumani" },
  ],
  navoiy: [
    { value: "navoiy_sh", label: "Navoiy shahri" },
    { value: "konimex", label: "Konimex tumani" },
    { value: "navbahor", label: "Navbahor tumani" },
    { value: "nurata", label: "Nurata tumani" },
    { value: "qiziltepa", label: "Qiziltepa tumani" },
    { value: "tomdi", label: "Tomdi tumani" },
    { value: "uchquduq", label: "Uchquduq tumani" },
    { value: "xatirchi", label: "Xatirchi tumani" },
    { value: "zarafshon", label: "Zarafshon shahri" },
  ],
  xorazm: [
    { value: "urganch", label: "Urganch shahri" },
    { value: "bogot", label: "Bo'g'ot tumani" },
    { value: "gurlan", label: "Gurlan tumani" },
    { value: "qoqon", label: "Qo'qon tumani" },
    { value: "qushkupir", label: "Qushkopir tumani" },
    { value: "xiva", label: "Xiva shahri" },
    { value: "xazorasp", label: "Xazorasp tumani" },
    { value: "shovot", label: "Shovot tumani" },
    { value: "yangiariq", label: "Yangiariq tumani" },
    { value: "yangibozor", label: "Yangibozor tumani" },
  ],
  qoraqalpogiston: [
    { value: "nukus", label: "Nukus shahri" },
    { value: "amudaryo", label: "Amudaryo tumani" },
    { value: "beruniy", label: "Beruniy tumani" },
    { value: "qongirot", label: "Qo'ng'irot tumani" },
    { value: "moynaq", label: "Mo'ynoq tumani" },
    { value: "muynak", label: "Muynaq tumani" },
    { value: "nukus_tum", label: "Nukus tumani" },
    { value: "taxtakoq", label: "Taxtako'pir tumani" },
    { value: "turtkul", label: "To'rtko'l tumani" },
    { value: "xojeli", label: "Xo'jayli tumani" },
    { value: "chimbay", label: "Chimboy tumani" },
    { value: "shumanay", label: "Shumanay tumani" },
    { value: "qoraozak", label: "Qorao'zak tumani" },
  ],
}

// Tuman label ni qisqartirish (tumani -> tuman, shahri -> shahar)
export const shortenDistrictLabel = (label: string): string => {
  return label.replace(' tumani', ' tuman').replace(' shahri', ' shahar')
}

// Viloyatni value bo'yicha topish
export const getRegionByValue = (value: string) => {
  return regions.find(r => r.value === value)
}

// Tumanni value bo'yicha topish
export const getDistrictByValue = (regionValue: string, districtValue: string) => {
  const districts = districtsByRegion[regionValue]
  return districts?.find(d => d.value === districtValue)
}